### ISSUE TITLE
add docs

### ISSUE THREAD

**Issue by sibelius** [camshaft/ast2template#7]

**Comment by mndvns** [comment]
@sibelius can you be more specific about the kind of docs you'd like to see?

**Comment by sibelius** [comment]
- [ ] motivation of this package
- [ ] examples of usage

**Comment by mndvns** [comment]
@sibelius the developers who use this library are already familiar with its motivations and usage. how did you learn about this library and what is your interest in it?

**Comment by mndvns** [comment]
closing this issue for now. FYI, @sibelius, i appreciate that you'd like some docs, but that's just not a priority for any of the folks who use this. perhaps in the future it will be.
